/CIA_WorldFactbook
    __init__.py
    /src
        __init__.py
        GetYoutubeFile.py
        ScraperPaths.py
        CIA_Abbreviations.py
        CIA_CountryComparisons.py
        CIA_CountryDetail.py
        CIA_CountryProfiles.py
        CIA_Definitions.py
        CIA_EnvironmentalAgreements.py
        CIA_ExtractComparisons.py
        CIA_FactbookMaster.py
        CIA_Faqs.py
        CIA_FlagsOfTheWorld.py
        CIA_Gallery.py
        CIA_History.py
        CIA_InternationalOrgnizationsAndGroups.py
        CIA_RefMaps.py
        CIA_ScanTools.py
        CIA_UsersGuide.py
        CIA_WeightsAndMeasures.py
        CIA_XrefCountryCodes.py
        CIA_XrefGeographicNames.py
        CIA_XrefHydrographicDataCodes.py
        GetPage.py
        ScraperPaths.py
